sudo: required

services:
  - docker

script:
  - docker-compose -f docker/docker-compose.yml up -d namenode hive-metastore-postgresql datanode hive-metastore hive-server && docker exec hive-server bash -c "git clone https://github.com/dharmeshkakadia/tpch-datagen-as-hive-query/ && cd tpch-datagen-as-hive-query && hive -i settings.hql -f TPCHDataGen.hql -hiveconf SCALE=10 -hiveconf PARTS=10 -hiveconf LOCATION=/HiveTPCH/ -hiveconf TPCHBIN=resources && hive -i settings.hql -f ddl/createAllExternalTables.hql -hiveconf LOCATION=/HiveTPCH/ -hiveconf DBNAME=tpch && for f in queries/*.hql; do STARTTIME=`date +%s`;  beeline -u jdbc:hive2://localhost:10000/tpch -i settings.hql -f $f > $f.out 2>&1 ; SUCCESS=$? ; ENDTIME=`date +%s`; echo $f,$SUCCESS,$STARTTIME,$ENDTIME ; done;"
